### ISSUE TITLE
有apk吗？

### ISSUE THREAD

**Issue by xuhj-code** [CJstar/HugeLocalImageLoad#1]
源码下到as里有配置不起来，简单的copy到eclipse里运行会有oom。。。

**Comment by Spring-Xu** [comment]
谢谢你的反馈，非常抱歉，我在添加参数做实验的时候再没有通过实验的情况下把代码提交了，麻烦你重新更新一下代码，或者看下[这个修改](https://github.com/Spring-Xu/HugeLocalImageLoad/commit/876abd15911cc7ac5fc7ec52bf9b6ae78c5ca1fe)，对应的修改一下代码再运行。

**Comment by xuhj-code** [comment]
好的，麻烦了
